#include <stdio.h>
/**
 * main - Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms. By starting with 1 and 2.
 * followed by a new line
 * Return: 0 (success)
 */

int main(void)
{
	int i = 0;
	long j = 1, k = 2, sum = k;

	while (k + j < 4000000)
	{
		k += j;
		if (k % 2 == 0)
			sum += k;
		j = k - j;
		++i;
	}
	printf("%ld\n", sum);
	return (0);
}
